# Generated by Django 4.2 on 2026-06-29 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformacaoContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(default='+258 87 250 1337', max_length=20)),
                ('whatsapp', models.CharField(default='+258 84 560 1278 / +258 86 143 2429', max_length=50)),
                ('email', models.EmailField(default='secretaria@instecnico.co.mz', max_length=254)),
                ('endereco', models.CharField(default='Av. União Africana, Casa Branca, Matola', max_length=200)),
                ('url_mapa_embed', models.TextField(default='https://www.google.com/maps/embed?pb=!1m17!1m12!1m3!1d3588.0116271856295!2d32.502157!3d-25.934842999999997!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m2!1m1!2zMjXCsDU2JzA1LjQiUyAzMsKwMzAnMDcuOCJF!5e0!3m2!1spt-PT!2smz!4v1781707179291!5m2!1spt-PT!2smz')),
                ('referencia_mapa', models.CharField(default='📍 Referência: Atrás das Bombas Total, na Papelaria Popular', max_length=200)),
            ],
            options={
                'verbose_name': 'Informação de Contacto',
                'verbose_name_plural': 'Informações de Contacto',
            },
        ),
        migrations.CreateModel(
            name='SecaoCursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Nossos Cursos Técnicos', max_length=100)),
                ('subtitulo', models.CharField(default='Formação completa e atualizada, com forte ligação ao mercado de trabalho.', max_length=200)),
                ('texto_chamada', models.CharField(default='Garanta a sua vaga', max_length=100)),
                ('link_chamada', models.CharField(default='index2.html#matriculas', max_length=200)),
            ],
            options={
                'verbose_name': 'Seção Cursos',
                'verbose_name_plural': 'Seções Cursos',
            },
        ),
        migrations.CreateModel(
            name='SecaoDepoimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='O que dizem os nossos alunos', max_length=100)),
                ('subtitulo', models.CharField(default='Depoimentos reais de quem já conquistou seu espaço no mercado', max_length=200)),
            ],
            options={
                'verbose_name': 'Seção Depoimentos',
                'verbose_name_plural': 'Seções Depoimentos',
            },
        ),
        migrations.CreateModel(
            name='SecaoEstatisticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Seção Estatísticas',
                'verbose_name_plural': 'Seções Estatísticas',
            },
        ),
        migrations.CreateModel(
            name='SecaoHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='LIGHT WORK', max_length=100)),
                ('subtitulo', models.CharField(default='Formando Profissionais para o Mercado de Trabalho', max_length=200)),
                ('descricao', models.TextField(default='Cursos Técnicos de Informática, Contabilidade, Eletricidade, Refrigeração e Climatização, e muito mais. Capacitação de excelência com foco em empregabilidade.')),
                ('preco', models.FloatField(default=800.0)),
                ('rotulo_preco', models.CharField(default='Cada curso', max_length=50)),
                ('info_parcelamento', models.CharField(default='parcelamento disponível', max_length=100)),
                ('texto_botao_primario', models.CharField(default='Matricular Agora', max_length=50)),
                ('link_botao_primario', models.CharField(default='#matriculas', max_length=200)),
                ('texto_botao_secundario', models.CharField(default='Conhecer Cursos', max_length=50)),
                ('link_botao_secundario', models.CharField(default='#cursos', max_length=200)),
            ],
            options={
                'verbose_name': 'Seção Hero',
                'verbose_name_plural': 'Seções Hero',
            },
        ),
        migrations.CreateModel(
            name='SecaoInfraestrutura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Infraestrutura de Ponta', max_length=100)),
                ('subtitulo', models.CharField(default='Ambientes preparados para o aprendizado prático e desenvolvimento profissional', max_length=200)),
            ],
            options={
                'verbose_name': 'Seção Infraestrutura',
                'verbose_name_plural': 'Seções Infraestrutura',
            },
        ),
        migrations.CreateModel(
            name='SecaoMatriculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='As Matrículas para 2026 Estão Abertas', max_length=100)),
                ('subtitulo', models.TextField(default='Garanta sua vaga e invista no futuro com cursos técnicos de alta empregabilidade. Condições especiais para matrícula antecipada.')),
                ('texto_botao', models.CharField(default='Inscrever-se Agora', max_length=50)),
                ('link_botao', models.CharField(default='#', max_length=200)),
            ],
            options={
                'verbose_name': 'Seção Matrículas',
                'verbose_name_plural': 'Seções Matrículas',
            },
        ),
        migrations.CreateModel(
            name='SecaoRodape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_instituto', models.CharField(default='INSTITUTO EDUCATIVO', max_length=100)),
                ('descricao', models.TextField(default='Instituto técnico referência em Maputo-Matola, formando profissionais com propósito e empregabilidade.')),
                ('horario_funcionamento', models.TextField(default='Segunda a Sexta: 8h - 20h\nSábado: 9h - 13h')),
                ('texto_copyright', models.CharField(default='© 2026 INSTITUTO EDUCATIVO. Todos os direitos reservados. Compromisso com a empregabilidade.', max_length=200)),
            ],
            options={
                'verbose_name': 'Seção Rodapé',
                'verbose_name_plural': 'Seções Rodapé',
            },
        ),
        migrations.CreateModel(
            name='SecaoSobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_distintivo', models.CharField(default='+1 mês de história', max_length=100)),
                ('titulo', models.CharField(default='Quem Somos', max_length=100)),
                ('missao', models.TextField(default='Capacitar profissionais com excelência técnica, ética e visão empreendedora, conectando-os ao mercado de trabalho.')),
                ('visao', models.TextField(default='Ser referência nacional em educação profissional técnica, reconhecida pela inovação e empregabilidade dos seus egressos.')),
                ('valores', models.TextField(default='Inovação, compromisso social, rigor técnico e parceria com a indústria.')),
                ('historia', models.TextField(default='Fundado em 2026, o Instituto Educativo já formou mais de 10 profissionais que atuam nas maiores empresas da região. Nossa metodologia combina teoria atualizada com prática intensiva em laboratórios.')),
                ('url_imagem', models.CharField(default='img/colleagues.jpg', max_length=255)),
            ],
            options={
                'verbose_name': 'Seção Sobre',
                'verbose_name_plural': 'Seções Sobre',
            },
        ),
        migrations.CreateModel(
            name='LinkSuporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('secao_rodape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_suporte', to='website.secaorodape')),
            ],
            options={
                'verbose_name': 'Link de Suporte',
                'verbose_name_plural': 'Links de Suporte',
            },
        ),
        migrations.CreateModel(
            name='LinkSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('secao_rodape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_sociais', to='website.secaorodape')),
            ],
            options={
                'verbose_name': 'Link Social',
                'verbose_name_plural': 'Links Sociais',
            },
        ),
        migrations.CreateModel(
            name='LinkRapido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('secao_rodape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_rapidos', to='website.secaorodape')),
            ],
            options={
                'verbose_name': 'Link Rápido',
                'verbose_name_plural': 'Links Rápidos',
            },
        ),
        migrations.CreateModel(
            name='ItemInfraestrutura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=200)),
                ('secao_infraestrutura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='website.secaoinfraestrutura')),
            ],
            options={
                'verbose_name': 'Item de Infraestrutura',
                'verbose_name_plural': 'Itens de Infraestrutura',
            },
        ),
        migrations.CreateModel(
            name='ItemEstatistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('rotulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, default='', max_length=200)),
                ('secao_estatisticas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='website.secaoestatisticas')),
            ],
            options={
                'verbose_name': 'Item Estatístico',
                'verbose_name_plural': 'Itens Estatísticos',
            },
        ),
        migrations.CreateModel(
            name='ImagemCarrossel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=255)),
                ('alt', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=False)),
                ('secao_hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_carrossel', to='website.secaohero')),
            ],
            options={
                'verbose_name': 'Imagem do Carrossel',
                'verbose_name_plural': 'Imagens do Carrossel',
            },
        ),
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citacao', models.TextField()),
                ('autor_nome', models.CharField(max_length=100)),
                ('autor_cargo', models.CharField(max_length=100)),
                ('icone_avatar', models.CharField(default='fas fa-user-circle', max_length=50)),
                ('secao_depoimentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depoimentos', to='website.secaodepoimentos')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('icone', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('imagem', models.CharField(max_length=255)),
                ('duracao', models.CharField(max_length=50)),
                ('pre_requisitos', models.CharField(max_length=200)),
                ('preco', models.CharField(max_length=20)),
                ('secao_cursos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='website.secaocursos')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
    ]
