# Generated by Django 5.0 on 2026-06-30 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemcarrossel',
            options={'ordering': ['-ativo', 'id'], 'verbose_name': 'Imagem do Carrossel', 'verbose_name_plural': 'Imagens do Carrossel'},
        ),
        migrations.RemoveField(
            model_name='imagemcarrossel',
            name='src',
        ),
        migrations.AddField(
            model_name='imagemcarrossel',
            name='imagem',
            field=models.ImageField(default=1, help_text='Formatos permitidos: JPG, JPEG, PNG, GIF, WEBP', max_length=255, upload_to='carrossel/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagem',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='imagemcarrossel',
            name='alt',
            field=models.CharField(max_length=255, verbose_name='Texto alternativo'),
        ),
        migrations.AlterField(
            model_name='imagemcarrossel',
            name='ativo',
            field=models.BooleanField(default=False, verbose_name='Ativo no carrossel'),
        ),
    ]
