# Generated by Django 5.0 on 2026-06-30 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_imagemcarrossel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secaosobre',
            name='url_imagem',
        ),
        migrations.AddField(
            model_name='secaosobre',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Formatos permitidos: JPG, JPEG, PNG, GIF, WEBP', max_length=255, null=True, upload_to='sobre/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
    ]
