# Generated by Django 5.0 on 2026-06-30 13:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_secaosobre_url_imagem_secaosobre_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secaohero',
            name='link_botao_primario',
            field=models.CharField(default="{% url 'matricula' %}", max_length=255),
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=20, verbose_name='Gênero')),
                ('nacionalidade', models.CharField(default='Moçambicana', max_length=100, verbose_name='Nacionalidade')),
                ('bilhete_identidade', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='BI/NUIT')),
                ('telefone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?258?[0-9]{9,12}$', 'Número inválido')], verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('endereco', models.TextField(max_length=300, verbose_name='Endereço')),
                ('forma_pagamento', models.CharField(choices=[('V', 'À vista'), ('P', 'Parcelado (3x)'), ('B', 'Bolsa/Desconto')], default='V', max_length=1, verbose_name='Forma de pagamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('C', 'Confirmada'), ('A', 'Aprovada'), ('R', 'Rejeitada'), ('M', 'Matriculado')], default='P', max_length=1, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de inscrição')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='website.curso', verbose_name='Curso pretendido')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
